name: Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '9.0.0'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Abdullahi_Elmi  # Replace with the correct relative path

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Abdullahi_Elmi  # Replace with the correct relative path

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Abdullahi_Elmi  # Replace with the correct relative path
